project:
  type: website

website:
  title: "Raychel Sun"
  favicon: "sun.jpg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: publication.qmd
        text: Publication
      - href: resource.qmd
        text: Resource   
      - href: gallery.qmd
        text: Gallery

    right:
      - text: LinkedIn
        url: "https://www.linkedin.com/in/raychelsun/"
        icon: linkedin
      - text: GitHub
        icon: github
        url: "https://github.com/rayxsun"
      - text: Email
        href: mailto:sunxiaoformal@gmail.com
        icon: envelope
      - text: Resume
        href: Sun_CV_ aug29.pdf
        icon: file-earmark-person

format:
  html:
    theme: materia
    css: mystyle.scss
    toc: true
    mainfont: Roboto
    fontsize: 18px
    linestretch: 1.7
    page-layout: article
    citations-hover: true
    code-link: true
    code-fold: show
    code-tools: false



